"""rename project name to title

Revision ID: c629d26ee958
Revises: 6e83a06d136c
Create Date: 2026-08-02 19:44:39.427033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c629d26ee958'
down_revision: Union[str, Sequence[str], None] = '6e83a06d136c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('title', sa.String(length=100), nullable=False))
    op.drop_column('projects', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_column('projects', 'title')
    # ### end Alembic commands ###
